import 'package:flutter/material.dart';

import 'models/transaction.dart';

class TransactionRepository {
  final List<Transaction> transactions = [
    Transaction(
      nameOfUser: 'Diana',
      payment: false,
      sum: 14.06,
      name: 'Apple',
      describe: 'Card number used',
      pending: true,
      dateTime: DateTime.now(),
      authorizedUser: true,
      icon: Icons.apple,
    ),
    Transaction(
      payment: true,
      sum: 174.00,
      describe: 'From another Bank',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(hours: 23)),
      authorizedUser: false,
      icon: Icons.flutter_dash,
    ),
    Transaction(
      nameOfUser: 'Diana',
      payment: false,
      sum: 3.24,
      name: 'Apple',
      describe: 'Card number used',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 1)),
      authorizedUser: true,
      icon: Icons.apple,
    ),
    Transaction(
      payment: true,
      sum: 99.71,
      describe: 'From JPMorgan Chase Bank National',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 2)),
      authorizedUser: false,
      icon: Icons.apple,
    ),
    Transaction(
      payment: true,
      sum: 73.58,
      describe: 'From JPMorgan Chase Bank National',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 3)),
      authorizedUser: false,
      icon: Icons.apple,
    ),
    Transaction(
      payment: false,
      sum: 21.61,
      name: 'IKEA',
      describe: 'Round Rock,TX',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 4)),
      authorizedUser: false,
      icon: Icons.apple,
    ),
    Transaction(
      payment: false,
      sum: 73.58,
      name: 'Target',
      describe: 'Cedar Park,TX',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 5)),
      authorizedUser: false,
      icon: Icons.apple,
    ),
    Transaction(
      payment: false,
      sum: 32.58,
      name: 'Silpo',
      describe: 'Mono',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 6)),
      authorizedUser: false,
      icon: Icons.store,
    ),
    Transaction(
      payment: false,
      sum: 59.12,
      name: 'Silpo',
      describe: 'Mono',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 7)),
      authorizedUser: false,
      icon: Icons.store,
    ),
    Transaction(
      payment: false,
      sum: 15.78,
      name: 'Silpo',
      describe: 'Mono',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 8)),
      authorizedUser: false,
      icon: Icons.store,
    ),
    Transaction(
      payment: false,
      sum: 19.52,
      name: 'Silpo',
      describe: 'Mono',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 9)),
      authorizedUser: false,
      icon: Icons.store,
    ),
    Transaction(
      payment: false,
      sum: 12.90,
      name: 'Silpo',
      describe: 'Mono',
      pending: false,
      dateTime: DateTime.now().subtract(const Duration(days: 10)),
      authorizedUser: false,
      icon: Icons.store,
    ),
  ];
}
